<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>16988f23-0757-4120-ae64-2b7f676fbc1f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <!-- reference the core library in src -->
    <ProjectReference Include="..\..\..\src\EmailLibraryCore\EmailLibrary\EmailLibrary.csproj">
      <Aliases></Aliases>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="EmailLibrary">
      <HintPath>..\..\..\src\EmailLibraryCore\EmailLibrary\bin\Debug\net8.0\EmailLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
