name: Build, Package, and Release .NET Framework 4.7.2

on:
  # pull_request:
  #   types: [closed]
  #   branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2.0.0

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages
        run: nuget restore .\EmailLibrary\EmailLibrary.sln

      - name: Build project
        run: |
          msbuild .\EmailLibrary\EmailLibrary.sln /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion="v4.7.2"

      - name: Create release directory
        run: mkdir release

      - name: Create library directory
        run: mkdir .\release\library

      - name: Copy build output to library directory
        run: |
          Get-ChildItem -path ".\EmailLibrary\EmailLibrary\bin\Release\" -Recurse -Exclude "*.pdb" | ForEach-Object {
            Try {
                Copy-Item $_ -Destination ".\release\library\"
            } Catch {
                Write-Warning "Could not load assembly: $_"
            }
          }

      - name: Copy powershell module to release directory
        run: |
          Copy-Item -Path ".\EmailLibrary\EmailModule\EmailModule.psd1" -Destination ".\release\"
          Copy-Item -Path ".\EmailLibrary\EmailModule\EmailModule.psm1" -Destination ".\release\"

      - name: Get File Hashes
        run: |
          Get-ChildItem -path ".\EmailLibrary\EmailLibrary\bin\Release\" -Recurse -Exclude "*.pdb" | ForEach-Object {
            Get-FileHash $_ -Algorithm SHA256 | FL | Out-File -FilePath ".\Hashes.txt" -Append
          }
          Get-FileHash -Path ".\EmailLibrary\EmailModule\EmailModule.psm1" -Algorithm SHA256 | FL | Out-File -FilePath ".\Hashes.txt" -Append
          Get-FileHash -Path ".\EmailLibrary\EmailModule\EmailModule.psd1" -Algorithm SHA256 | FL | Out-File -FilePath ".\Hashes.txt" -Append

      - name: Zip the release directory
        run: Compress-Archive -Path ".\release\*" -DestinationPath "EmailModule.zip"

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: EmailModule.zip,Hashes.txt
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
