name: Build and Test PowerShell Module

on:
  push:
    branches: [ working ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.TOKEN }}

      - name: Setup MSBuild .NET Framework Build
        uses: microsoft/setup-msbuild@v2.0.0

      - name: Setup NuGet .NET Framework Build
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore NuGet packages for .NET Framework Build
        run: nuget restore .\EmailLibraryDesktop\EmailLibrary.sln

      - name: Build .NET Framework project
        run: |
          msbuild .\EmailLibraryDesktop\EmailLibrary.sln /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion="v4.7.2"

      - name: Create release directories
        run: |
          mkdir release
          mkdir .\release\Tests
          mkdir .\release\lib
          mkdir .\release\lib\Core
          mkdir .\release\lib\Desktop

      - name: Copy .NET Framework build output to lib Desktop directory
        run: |
          Get-ChildItem -path ".\EmailLibraryDesktop\EmailLibrary\bin\Release\" -Recurse -Exclude "*.pdb" | ForEach-Object {
            Copy-Item $_ -Destination ".\release\lib\Desktop\"
          }

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: "8.0.x"

      - name: Install dependencies .NET Core Build
        run: dotnet restore .\EmailLibraryCore\EmailLibrary\EmailLibrary.csproj

      - name: Build .NET Core project
        run: dotnet build .\EmailLibraryCore\EmailLibrary\EmailLibrary.csproj --configuration Release --no-restore

      - name: Publish .NET Core project
        run: dotnet publish .\EmailLibraryCore\EmailLibrary\EmailLibrary.csproj --configuration Release --no-restore --output publish
        env:
            PublishRelease: true

      - name: Copy .NET Core publish output to lib Core directory
        run: |
          Get-ChildItem -path ".\publish\" -Exclude "*.pdb" | Where-Object Attributes -ne Directory | ForEach-Object {
            Copy-Item $_ -Destination ".\release\lib\Core\"
          }

      - name: Generate Powershell Manifest
        run: |
          $files = @('.\EmailModule.psd1','.\EmailModule.psm1','.\EmailModule.Libraries.ps1')
          Get-ChildItem -Path ".\release\" -Recurse | ForEach-Object { 
              $files += $_.FullName.ToString().Replace('D:\a\Powershell_Email-Module\Powershell_Email-Module\release','.') 
          }
          $version = '${{ steps.tag_version.outputs.new_tag }}'
          $version = $version  -replace 'v', ''
          $version = $version  -replace "-working*", ''
          $moduleSettings = @{
            Path = '.\EmailModule\EmailModule.psd1'

            # Script module or binary module file associated with this manifest.
            RootModule = 'EmailModule.psm1'

            # Version number of this module.
            ModuleVersion = $version

            # Supported PSEditions
            CompatiblePSEditions = @('Desktop','Core')

            # ID used to uniquely identify this module
            GUID = '6f8c4c8a-6e0d-4139-836c-f798b30ada92'

            # Author of this module
            Author = 'Brandon Navarro'

            # Company or vendor of this module
            CompanyName = 'None'

            # Copyright statement for this module
            Copyright = '(c) Brandon Navarro. All rights reserved.'

            # Description of the functionality provided by this module
            Description = 'Powershell Module to send Email using MailKit, MimeKit and STARTTLS'

            # Minimum version of the PowerShell engine required by this module
            PowerShellVersion = '5.1'

            # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
            DotNetFrameworkVersion = '4.7.2'

            # Processor architecture (None, X86, Amd64) required by this module
            ProcessorArchitecture = 'None'

            # Script files (.ps1) that are run in the caller's environment prior to importing this module.
            ScriptsToProcess = @('EmailModule.Libraries.ps1')

            # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
            FunctionsToExport = 'Send-Email'

            # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
            CmdletsToExport = 'Send-Email'

            # Variables to export from this module
            VariablesToExport = @()

            # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
            AliasesToExport = @()

            # List of all files packaged with this module
            FileList = $files
          }
          New-ModuleManifest @moduleSettings

      - name: Copy powershell module to release directory
        run: |
          Copy-Item -Path ".\EmailModule\EmailModule.Libraries.ps1" -Destination ".\release\"
          Copy-Item -Path ".\EmailModule\EmailModule.psd1" -Destination ".\release\"
          Copy-Item -Path ".\EmailModule\EmailModule.psm1" -Destination ".\release\"

      - name: Copy powershell test to release directory
        run: |
          Copy-Item -Path ".\Tests\EmailModule.Tests.ps1" -Destination ".\release\Tests\"

      - name: Package Module to artifacts
        run: |
            New-Item -ItemType Directory -Path 'artifact' | Out-Null;
            Copy-Item -Recurse -Force .\release\* .\artifact\
            Get-ChildItem -path ".\release\" -Recurse -File | ForEach-Object {
              Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256 | FL | Out-File -FilePath ".\Hashes.txt" -Append
            }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: EmailModule
          path: |
            artifact/
            Hashes.txt
          if-no-files-found: error

  test:
    name: Test Module on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: EmailModule
          path: EmailModule

      - name: Verify module manifest
        shell: pwsh
        run: |
          Test-ModuleManifest -Path '.\EmailModule\artifact\EmailModule.psd1'

      - name: Test Module
        shell: pwsh
        run: |
          $Linux = $IsLinux
          $MacOS = $IsMacOS
          $Windows = $IsWindows
          Import-Module .\EmailModule\artifact\EmailModule.psm1
          $AuthUser = "${{ secrets.AUTHUSER }}"
          $AuthPass = "${{ secrets.AUTHPASS }}"
          $To = "${{ secrets.TO }}"
          $ToName = "Brandon Navarro"
          $From = "${{ secrets.AUTHUSER }}"
          $FromName = "Brandon Navarro"
          $Subject = "Github Actions ${{ matrix.os }} PSEdition: $PSEdition"
          $Body = "
            test, Test, TEST!, dotnet Core Email Module

            Linux: $Linux
            MacOS: $MacOS
            Windows: $Windows
            PSEdition: $PSEdition

            This is a GitHub Actions Automated Test
          "
          $MailServer = "${{ secrets.MAILSERVER }}"
          $ServerPort = "587"
          Send-Email -AuthUser $AuthUser -AuthPass $AuthPass `
              -EmailTo $To -EmailToName $ToName `
              -EmailFrom $From -EmailFromName $FromName `
              -Subject $Subject -Body $Body `
              -SmtpServer $MailServer -SmtpPort $ServerPort

  windows_test:
    runs-on: windows-latest
    name: Test Module on windows-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: EmailModule
          path: EmailModule

      - name: Test Module with Powershell Desktop
        shell: powershell
        run: |
          Import-Module .\EmailModule\artifact\EmailModule.psm1
          $AuthUser = "${{ secrets.AUTHUSER }}"
          $AuthPass = "${{ secrets.AUTHPASS }}"
          $To = "${{ secrets.TO }}"
          $ToName = "Brandon Navarro"
          $From = "${{ secrets.AUTHUSER }}"
          $FromName = "Brandon Navarro"
          $Subject = "Github Actions windows-latest PSEdition: $PSEdition"
          $Body = "
            test, Test, TEST!, dotNET Framework Email Module

            PSEdition: $PSEdition

            This is a GitHub Actions Automated Test
          "
          $MailServer = "${{ secrets.MAILSERVER }}"
          $ServerPort = "587"
          Send-Email -AuthUser $AuthUser -AuthPass $AuthPass `
              -EmailTo $To -EmailToName $ToName `
              -EmailFrom $From -EmailFromName $FromName `
              -Subject $Subject -Body $Body `
              -SmtpServer $MailServer -SmtpPort $ServerPort
